apiVersion: apps/v1
kind: Deployment
metadata:
  name: captive-portal-deployment
  namespace: mynamespace
  labels:
    app: captive-portal
spec:
  selector:
    matchLabels:
      app: captive-portal
  replicas: 3
  template:
    metadata:
      labels:
        app: captive-portal
    spec:
      containers:
      - name: captive-portal
        image: stanley22/captive-portal:v1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
