# https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: marcelin-ingress-class
spec:
  controller: k8s.io/ingress-nginx
