apiVersion: v1
kind: Service
metadata:
  name: captive-portal-service
  namespace: mynamespace
spec:
  selector:
    app: captive-portal
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: captive-portal-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
